<?php

return array(

	//Product import template
	'IMPORT_PRODUCT' => array(
		'A' => '产品编码', 
		'B' => '中文名称',
		'C' => '英文名称',
		'D' => '价格￥',
		'E' => '发货重量g',
		'F' => '包装长cm',
		'G' => '包装宽cm',
		'H' => '包装高cm',
		'I' => '是否带电',
		'J' => '德国头程方式',
		'K' => '美国头程方式',
		'L' => '美国关税率',
		'M' => '德国关税率',
		'N' => '预计采购用时天',
		'O' => '产品经理',
		'P' => '供货商编号',
		'Q' => '采购链接',
		'R' => 'greatgoodshop自建仓售价$',
		'S' => 'rc-helicar万邑联美国售价$',
		'T' => 'rc-helicar万邑联德国售价€',
		'U' => 'ebay.com销量链接',
		'V' => 'ebay.com最低价链接',
		'W' => 'ebay.de销量链接',
		'X' => 'ebay.de最低价链接',
		),

	//Inbound_item import template
	'IMPORT_INBOUND_ITEM' => array(
		'A' => '补货表编号',
		'B' => '产品编码',
		'C' => '数量',
		),

	//Inbound_item import template
	'IMPORT_INBOUND_PACKAGE' => array(
		'A' => '编号',
		'B' => '重量kg',
		'C' => '长度cm',
		'D' => '宽度cm',
		'E' => '高度cm',
		),

	//Ebay en order tamplate
	'IMPORT_EBAY_EN_ORDER' => array(
		'A' => 'Sales Record Number',
		'B' => 'User Id',
		'C' => 'Buyer Fullname',
		'D' => 'Buyer Phone Number',
		'E' => 'Buyer Email',
		'F' => 'Buyer Address 1',
		'G' => 'Buyer Address 2',
		'H' => 'Buyer City',
		'I' => 'Buyer State',
		'J' => 'Buyer Zip',
		'K' => 'Buyer Country',
		'L' => 'Order ID',
		'M' => 'Item ID',
		'N' => 'Transaction ID',
		'O' => 'Item Title',
		'P' => 'Quantity',
		'Q' => 'Sale Price',
		'R' => 'Shipping And Handling',
		'S' => 'Sales Tax',
		'T' => 'Insurance',
		'U' => 'eBay Collected Tax',
		'V' => 'Total Price',
		'W' => 'Payment Method',
		'X' => 'PayPal Transaction ID',
		'Y' => 'Sale Date',
		'Z' => 'Checkout Date',
		'AA' => 'Paid on Date',
		'AB' => 'Shipped on Date',
		'AC' => 'Shipping Service',
		'AD' => 'Feedback Left',
		'AE' => 'Feedback Received',
		'AF' => 'Notes to Yourself',
		'AG' => 'Custom Label',
		),

	//Ebay de order tamplate
	'IMPORT_EBAY_DE_ORDER' => array(
		'A' => 'Verkaufsprotokollnumm',
		'B' => 'Nutzername',
		'C' => 'Name des Käufers',
		'D' => 'Telefonnummer',
		'E' => 'E-Mail-Adresse',
		'F' => 'Adresse 1',
		'G' => 'Adresse 2',
		'H' => 'Ort',
		'I' => 'Region',
		'J' => 'PLZ',
		'K' => 'Land',
		'L' => 'Artikelnummer',
		'M' => 'Artikelbezeichnung',
		'N' => 'Bestandseinheit',
		'O' => 'Stückzahl',
		'P' => 'Preis',
		'Q' => 'MwSt.-Satz',
		'R' => 'Verpackung und Versand',
		'S' => 'Versicherung',
		'T' => 'Nachnahmekosten',
		'U' => 'Gesamtpreis',
		'V' => 'Zahlungsmethode',
		'W' => 'Verkauft am',
		'X' => 'Datum der Kaufabwicklung',
		'Y' => 'Zahlungsdatum',
		'Z' => 'Versanddatum',
		'AA' => 'Rechnungsdatum',
		),

	//Purchase order template
	'IMPORT_PURCHASE' => array(
		'A' => '临时编号',
		'B' => '产品编码',
		'C' => '单价',
		'D' => '数量',
		'E' => '运费',
		'F' => '仓库',
		'G' => '产品经理',
		'H' => '供货商编号',
		'I' => '订单号',
		'J' => '追踪号',
		'K' => '备注',
		),

	//Winit storage template
	'IMPORT_WINIT_STORAGE' => array(
		'A' => '商品编号',
		'B' => '中文名称',
		'C' => '英文名称',
		'D' => '备注',
		'E' => '历史入库',
		'F' => '规格',
		'G' => '可用库存',
		'H' => '待出库',
		'I' => '在途库存',
		'J' => '存储模式库存',
		'K' => '历史销量',
		'L' => '30天平均日销量',
		'M' => '30天平均库存',
		'N' => '15天平均日销量',
		'O' => '15天平均库存',
		'P' => '7天平均日销量',
		'Q' => '7天平均库存',
		'R' => 'DOI',
		'S' => '禁止出库库存',
		'T' => '禁止出库',
		),

	//Winit storage template
	'IMPORT_WINIT_STORAGE_SHEET' => array(
		0 => '万邑通美西库存表',
		1 => '万邑通德国库存表',
		),

	//update restock shipping status for other warehosue
	'IMPORT_UPDATE_RESTOCK_SHIPPING_STATUS' => array(
		'A' => '补货表编号',
		'B' => '商品编码',
		'C' => '数量',
		'C' => '状态',
		),

	//update product packing weight length widht height from winit product template
	'IMPORT_WINIT_PRODUCT' => array(
		'A'=>'商品条码',
		'B'=>'编码',
		'C'=>'规格',
		'D'=>'中文名称',
		'E'=>'英文名称',
		'F'=>'注册重量(kg)',
		'G'=>'重量体积固定',
		'H'=>'注册长(cm)',
		'I'=>'注册宽(cm)',
		'J'=>'注册高(cm)',
		'K'=>'注册体积(CBM)',
		'L'=>'有品牌',
		'M'=>'有电池',
		'N'=>'商品展示页网址',
		'O'=>'备注',
		'P'=>'出口地',
		'Q'=>'禁止入库',
		'R'=>'出口申报价值(USD)',
		'S'=>'进口国家',
		'T'=>'进口申报价值(USD)',
		'U'=>'海关建议申报价值(USD)',
		'V'=>'采购成本(USD)',
		'W'=>'确认重量(kg)',
		'X'=>'确认长(cm)',
		'Y'=>'确认宽(cm)',
		'Z'=>'确认高(cm)',
		'AA'=>'体积(CBM)',
		'AB'=>'货型',
		'AC'=>'出口退税率',
		'AD'=>'监管条件',
		'AE'=>'头程类型',
		'AF'=>'有效',
		'AG'=>'进口关税税率',
		),

	//import winit outbound template
	'IMPORT_WINIT_OUTBOUND' => array(
		'A'=>'Seller Order NO.',
		'B'=>'Warehouse',
		'C'=>'Shipping Method',
		'D'=>'Value-added service 1',
		'E'=>'Value-added service 2',
		'F'=>'Insured amount',
		'G'=>'VATNo',
		'H'=>'eBaySellerID',
		'I'=>'eBayBuyerID',
		'J'=>'Buyer Fullname',
		'K'=>'Buyer Phone Number',
		'L'=>'Buyer Email',
		'M'=>'Buyer Address 1',
		'N'=>'Buyer Address 2',
		'O'=>'Buyer City',
		'P'=>'Buyer State',
		'Q'=>'Buyer Postcode',
		'R'=>'Buyer Country',
		'S'=>'House No.',
		'T'=>'Duplicate order',
		'U'=>'SKU No.',
		'V'=>'Attribute',
		'W'=>'Quantity',
		'X'=>'Item Number',
		'Y'=>'Transaction ID',
		),

	//update ebay file exchange template column name
	'IMPORT_EBAY_FXT' => array(
		'A'=>'Action',
		'B'=>'ItemID',
		'C'=>'Title',
		'D'=>'SiteID',
		'E'=>'Currency',
		'F'=>'StartPrice',
		'G'=>'BuyItNowPrice',
		'H'=>'Quantity',
		'I'=>'Relationship',
		'J'=>'RelationshipDetails',
		'K'=>'CustomLabel',
		),

	//update amazon file exchange template column name
	'IMPORT_AMAZON_FXT' => array(
		'A'=>'sku',
		'B'=>'price',
		'C'=>'minimum-seller-allowed-price',
		'D'=>'maximum-seller-allowed-price',
		'E'=>'quantity',
		'F'=>'leadtime-to-ship',
		'G'=>'fulfillment-channel',
		),

	//accounting amazon transaction view template column name
	'IMPORT_AMAZON_TV' => array(
		'A'=>'Date',
		'B'=>'Order ID',
		'C'=>'SKU',
		'D'=>'Transaction type',
		'E'=>'Payment Type',
		'F'=>'Payment Detail',
		'G'=>'Amount',
		'H'=>'Quantity',
		'I'=>'Product Title',
		),

	//update groupon file exchange template column name
	'IMPORT_GROUPON_FXT' => array(
		'A'=>'Product Title',
		'B'=>'Variant 1',
		'C'=>'Variant 2',
		'D'=>'Variant 3',
		'E'=>'Product ID',
		'F'=>'Option ID',
		'G'=>'Location ID',
		'H'=>'Product State',
		'I'=>'QTY sold',
		'J'=>'QTY available',
		'K'=>'SKU',
		'L'=>'UPC',
		'M'=>'MSRP Price',
		'N'=>'Market Rate Price',
		'O'=>'Groupon Price',
		),

	//Amazon Unshipped orders template
	'IMPORT_AMAZON_UNSHIPPED_ORDER' => array(
		'A' => 'order-id',
		'B' => 'order-item-id',
		'C' => 'purchase-date',
		'D' => 'payments-date',
		'E' => 'reporting-date',
		'F' => 'promise-date',
		'G' => 'days-past-promise',
		'H' => 'buyer-email',
		'I' => 'buyer-name',
		'J' => 'buyer-phone-number',
		'K' => 'sku',
		'L' => 'product-name',
		'M' => 'quantity-purchased',
		'N' => 'quantity-shipped',
		'O' => 'quantity-to-ship',
		'P' => 'ship-service-level',
		'Q' => 'ship-service-name',
		'R' => 'recipient-name',
		'S' => 'ship-address-1',
		'T' => 'ship-address-2',
		'U' => 'ship-address-3',
		'V' => 'ship-city',
		'W' => 'ship-state',
		'X' => 'ship-postal-code',
		'Y' => 'ship-country',
		'Z' => 'payment-method',
		),

	//Groupon Unshipped orders template
	'IMPORT_GROUPON_UNSHIPPED_ORDER' => array(
		'A' => 'fulfillment_line_item_id',
		'B' => 'groupon_number',
		'C' => 'order_date',
		'D' => 'merchant_sku_item',
		'E' => 'quantity_requested',
		'F' => 'shipment_method_requested',
		'G' => 'shipment_address_name',
		'H' => 'shipment_address_street',
		'I' => 'shipment_address_street_2',
		'J' => 'shipment_address_city',
		'K' => 'shipment_address_stat',
		'L' => 'shipment_address_postal_code',
		'M' => 'shipment_address_country',
		'N' => 'gift',
		'O' => 'gift_message',
		'P' => 'quantity_shipped',
		'Q' => 'shipment_carrier',
		'R' => 'shipment_method',
		'S' => 'shipment_tracking_number',
		'T' => 'ship_date',
		'U' => 'groupon_sku',
		'V' => 'custom_field_value',
		'W' => 'permalink',
		'X' => 'item_name',
		'Y' => 'vendor_id',
		'Z' => 'salesforce_deal_option_id',
		'AA' => 'groupon_cost',
		'AB' => 'billing_address_name',
		'AC' => 'billing_address_street',
		'AD' => 'billing_address_city',
		'AE' => 'billing_address_stat',
		'AF' => 'billing_address_postal_code',
		'AG' => 'billing_address_country',
		'AH' => 'purchase_order_number',
		'AI' => 'product_weight',
		'AJ' => 'product_weight_unit',
		'AK' => 'product_length',
		'AL' => 'product_width',
		'AM' => 'product_height',
		'AN' => 'product_dimension_unit',
		'AO' => 'customer_phone',
		'AP' => 'incoterms',
		'AQ' => 'hts_code',
		'AR' => '3pl_name',
		'AS' => '3pl_warehouse_location',
		'AT' => 'kitting_details',
		'AU' => 'sell_price',
		'AV' => 'deal_opportunity_id',
		'AW' => 'shipment_strategy',
		'AX' => 'fulfillment_method',
		'AY' => 'country_of_origin',
		'AZ' => 'merchant_permalink',
		'BA' => 'feature_start_date',
		'BB' => 'feature_end_date',
		'BC' => 'bom_sku',
		'BD' => 'parent_order_id',
		),

	//Groupon order analysis template
	'IMPORT_GROUPON_ORDER_ANALYZE' => array(
		'A' => 'Merhant Name',
		'B' => 'Merchant Id',
		'C' => 'Product Title',
		'D' => 'Product Id',
		'E' => 'Order State',
		'F' => 'Shipment State',
		'G' => 'Paid',
		'H' => 'Waiting Postage Date',
		'I' => 'Uploaded Date',
		'J' => 'Transit Date',
		'K' => 'Fulfilled Date',
		'L' => 'Delivered Date',
		'M' => 'Canceled Date',
		'N' => 'Returned Date',
		'O' => 'Product Price',
		'P' => 'Tax Amount',
		'Q' => 'Shipping Amount',
		'R' => 'Commission Amount',
		'S' => 'Commission Rate',
		'T' => 'Support Id',
		'U' => 'Legacy Id',
		'V' => 'Shipping Carrier',
		'W' => 'Tracking Number',
		'X' => 'Deal Permalink',
		'Y' => 'Product Deal Type',
		'Z' => 'Product Promoted',
		'AA' => 'Return Policy',
		'AB' => 'Is Pickup Order',
		'AC' => 'Pickup Location Id',
		'AD' => 'Order Expiration Date',
		'AE' => 'Sku',
		),

	//Groupon order analysis template
	'IMPORT_EXCLUDE_STOCK_FXT' => array(
		'A' => 'Sku',
		'B' => 'Quantity',
		),

	//Amazon Us Storage template
	'IMPORT_AMAZON_US_STORAGE' => array(
		'A' => 'Country',
		'B' => 'Product Description',
		'C' => 'FNSKU',
		'D' => 'SKU',
		'E' => 'ASIN',
		'F' => 'Condition',
		'G' => 'Supplier',
		'H' => 'Supplier part no.',
		'I' => 'Currency Code',
		'J' => 'Price',
		'K' => 'Sales last 30 days (sales)',
		'L' => 'Sales last 30 days (units)',
		'M' => 'Total Inventory',
		'N' => 'Inbound Inventory',
		'O' => 'Available Inventory',
		'P' => 'Reserved - FC transfer',
		'Q' => 'Reserved - FC processing',
		'R' => 'Reserved - Customer Order',
		'S' => 'Unfulfillable',
		'T' => 'Fulfilled by',
		'U' => 'Days of Supply',
		'V' => 'Instock Alert',
		'W' => 'Recommended Order Quantity',
		'X' => 'Recommended Order Date',
		),
	//Amazon FBA orders template
	'IMPORT_AMAZON_FBA_ORDER' => array(
		'A' => 'amazon-order-id',
		'B' => 'merchant-order-id',
		'C' => 'shipment-id',
		'D' => 'shipment-item-id',
		'E' => 'amazon-order-item-id',
		'F' => 'merchant-order-item-id',
		'G' => 'purchase-date',
		'H' => 'payments-date',
		'I' => 'shipment-date',
		'J' => 'reporting-date',
		'K' => 'buyer-email',
		'L' => 'buyer-name',
		'M' => 'buyer-phone-number',
		'N' => 'sku',
		'O' => 'product-name',
		'P' => 'quantity-shipped',
		'Q' => 'currency',
		'R' => 'item-price',
		'S' => 'item-tax',
		'T' => 'shipping-price',
		'U' => 'shipping-tax',
		'V' => 'gift-wrap-price',
		'W' => 'gift-wrap-tax',
		'X' => 'ship-service-level',
		'Y' => 'recipient-name',
		'Z' => 'ship-address-1',
		'AA' => 'ship-address-2',
		'AB' => 'ship-address-3',
		'AC' => 'ship-city',
		'AD' => 'ship-state',
		'AE' => 'ship-postal-code',
		'AF' => 'ship-country',
		'AG' => 'ship-phone-number',
		'AH' => 'bill-address-1',
		'AI' => 'bill-address-2',
		'AJ' => 'bill-address-3',
		'AK' => 'bill-city',
		'AL' => 'bill-state',
		'AM' => 'bill-postal-code',
		'AN' => 'bill-country',
		'AO' => 'item-promotion-discount',
		'AP' => 'ship-promotion-discount',
		'AQ' => 'carrier',
		'AR' => 'tracking-number',
		'AS' => 'estimated-arrival-date',
		'AT' => 'fulfillment-center-id',
		'AU' => 'fulfillment-channel',
		'AV' => 'sales-channel',
		),

	//Ebay en waiting shipping order template
	'IMPORT_EBAY_WAITING_SHIPPING_EN_ORDER' => array(
		'A' => 'Sales Record Number',
		'B' => 'User Id',
		'C' => 'Buyer Fullname',
		'D' => 'Buyer Phone Number',
		'E' => 'Buyer Email',
		'F' => 'Buyer Address 1',
		'G' => 'Buyer Address 2',
		'H' => 'Buyer City',
		'I' => 'Buyer State',
		'J' => 'Buyer Zip',
		'K' => 'Buyer Country',
		'L' => 'Item Number',
		'M' => 'Item Title',
		'N' => 'Custom Label',
		'O' => 'Quantity',
		'P' => 'Sale Price',
		'Q' => 'Shipping and Handling',
		'R' => 'US Tax',
		'S' => 'Insurance',
		'T' => 'Cash on delivery fee',
		'U' => 'Total Price',
		'V' => 'Payment Method',
		'W' => 'Sale Date',
		'X' => 'Checkout Date',
		'Y' => 'Paid on Date',
		'Z' => 'Shipped on Date',
		'AA' => 'Feedback left',
		'AB' => 'Feedback received',
		'AC' => 'Notes to yourself',
		'AD' => 'Unique Product Id',
		'AE' => 'Private Field',
		'AF' => 'ProductIDType',
		'AG' => 'ProductIDValue',
		'AH' => 'ProductIDValue-2',
		'AI' => 'PayPal Transaction ID',
		'AJ' => 'Shipping Service',
		'AK' => 'Cash on delivery option',
		'AL' => 'Transaction ID',
		'AM' => 'Order ID',
		'AN' => 'Variation Details',
		),
	);
?>